import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Aboutus from "@/components/Aboutus";
import Footer from "@/components/Footer";


import Head from "next/head";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Hero heading='Find your comfort HERE' message='Get your good sleep with HERE!'/>
    <Aboutus/> 
    <Footer/>
    </div>
  );
}
